# Generated by Django 4.2.27 on 2025-12-11 15:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='purchase_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
